import { Suspense } from "react";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import QueryProvider from '@/providers/QueryProvider';
import { GlobalProvider } from "@/contexts/GlobalContext";
import { DEFAULT_SERVER_SORT } from '@/config/constants'

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Suspense>
          <GlobalProvider defaultSort={DEFAULT_SERVER_SORT}>
            <QueryProvider>
              {children}
            </QueryProvider>
          </GlobalProvider>
        </Suspense>
      </body>
    </html>
  );
}
